[package]
name = "backseat-collector"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16.0"
wasmtime = "32.0.0"
bsc-brain = { path = "../bsc-brain", default-features = false }
wasmtime-wasi = "32.0.0"
zerocopy = "0.8.25"
