[package]
name = "bsc-brain"
version = "0.1.0"
edition = "2024"

[dependencies]
zerocopy = { version = "0.8.25", features = ["derive"] }

[features]
default = ["native"]
native = []

[[example]]
name = "ping"
crate-type = ["cdylib"]
